name: Build APK

on:
  push:
    branches:
      - main  # Запускать сборку при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать сборку при пул-реквесте в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Указываем версию Python

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          # Скачиваем Android Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O /tmp/android-sdk.zip
          unzip /tmp/android-sdk.zip -d /tmp/android-sdk

          # Проверяем структуру распакованных файлов
          ls -la /tmp/android-sdk

          # Создаем директорию для Android SDK
          mkdir -p ~/.android/cmdline-tools

          # Перемещаем tools в правильную директорию
          mv /tmp/android-sdk/tools ~/.android/cmdline-tools/tools

          # Настраиваем переменные окружения
          echo "ANDROID_HOME=$HOME/.android" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.android/cmdline-tools/tools/bin" >> $GITHUB_ENV

          # Принимаем лицензии Android SDK
          yes | $HOME/.android/cmdline-tools/tools/bin/sdkmanager --licenses

          # Устанавливаем необходимые компоненты
          $HOME/.android/cmdline-tools/tools/bin/sdkmanager "build-tools;30.0.3" "platform-tools" "platforms;android-30"

          # Проверяем наличие AIDL
          $HOME/.android/build-tools/30.0.3/aidl --version || echo "AIDL not found, installing..."
          echo "PATH=$PATH:$HOME/.android/build-tools/30.0.3" >> $GITHUB_ENV

      - name: Run Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk  # Путь к собранному APK
