name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          # Download and extract Android Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O /tmp/android-sdk.zip
          unzip /tmp/android-sdk.zip -d ~/.android/cmdline-tools

          # Move extracted files to 'latest' directory
          mkdir -p ~/.android/cmdline-tools/latest
          mv ~/.android/cmdline-tools/tools/* ~/.android/cmdline-tools/latest/

          # Set environment variables
          echo "ANDROID_HOME=$HOME/.android" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/build-tools/31.0.0:$HOME/.android/platform-tools:$PATH" >> $GITHUB_ENV

          # Load updated PATH
          source $GITHUB_ENV

          # Accept licenses
          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install required SDK components
          ~/.android/cmdline-tools/latest/bin/sdkmanager "build-tools;31.0.0" "platform-tools" "platforms;android-31"

          # Verify AIDL installation
          if [ ! -f "$HOME/.android/build-tools/31.0.0/aidl" ]; then
            echo "AIDL not found, installation failed!"
            exit 1
          fi

      - name: Run Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk
